### ISSUE TITLE
Remove GUIDs from link objects displays to improve readability

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/flukes#14]

**Comment by ibaldin** [comment]
Fixed in a2663da831ddef805fc4b63c45adc156574b286f

**Comment by hinchliff** [comment]
Looks like this change (a2663da) affects the names displayed for nodes in NodeGroups.  All nodes in a NodeGroup0 are simply named `NodeGroup0`, without the usual qualifier at the end, e.g. `NodeGroup0/1`.
