### ISSUE TITLE
Insert guest SSH key: Pressing cancel button does not work properly

### ISSUE THREAD

**Issue by mcevik0** [RENCI-NRIG/flukes#20]
- Open "Insert guest SSH key" window. Enter a username. Press "cancel" button.
<img width="821" alt="screen shot 2017-12-31 at 12 59 29" src="https://user-images.githubusercontent.com/18286650/34463469-06c79a58-ee2b-11e7-95a2-62020cfde2b1.png">

- Message for successful insertion of the keys returns. 
<img width="519" alt="screen shot 2017-12-31 at 13 00 07" src="https://user-images.githubusercontent.com/18286650/34463488-56f7dc4a-ee2b-11e7-9c8f-fae9ed2de332.png">

- On the VMs, user account is created (with sudo access if sudo option is selected). No SSH keys is inserted (as expected). Pressing cancel button with no input still returns same message for successful insertion of the keys.

Flukes version:
<img width="741" alt="screen shot 2017-12-31 at 13 09 12" src="https://user-images.githubusercontent.com/18286650/34463508-f2594e12-ee2b-11e7-980a-d2032cad3a50.png">

**Comment by ibaldin** [comment]
Woops
