### ISSUE TITLE
Storage has disconnected link

### ISSUE THREAD

**Issue by mcevik0** [RENCI-NRIG/flukes#22]
A slice with a storage reservations has a possible visualization issue. This should be introduced recently. (I verified that previous version of Flukes does not have this issue).

Request with storage:
<img width="1312" alt="screen shot 2018-01-05 at 22 26 32" src="https://user-images.githubusercontent.com/18286650/34636209-841f0fac-f26a-11e7-9442-8edd5a8c52c1.png">

Manifest:
<img width="1312" alt="screen shot 2018-01-05 at 22 30 07" src="https://user-images.githubusercontent.com/18286650/34636228-c7dc4c1e-f26a-11e7-9e65-60b0ed98d933.png">

[manifest-storage.txt](https://github.com/RENCI-NRIG/flukes/files/1608458/manifest-storage.txt)

ORCA version:
ORCA FLUKES v.0.7.2.build-gitd6cea								built on 01/02/2018 17:09

**Comment by ibaldin** [comment]
should be fixed in 0.7.3
