### ISSUE TITLE
Flukes does not show correct bandwidth for links

### ISSUE THREAD

**Issue by kthare10** [RENCI-NRIG/flukes#25]
Flukes does not show correct bandwidth for links
Enclosed rdf has broadcast link bandwidth set to 1gbps and stitchport bandwidths set to 2.5gbps but flukes indicates it as 10mbps
[manifest.rdf.txt](https://github.com/RENCI-NRIG/flukes/files/3242192/manifest.rdf.txt)

NOTE: rename the manifest file, github didn't allow to upload file with extensions .rdf

**Comment by ibaldin** [comment]
The patch above fixes it in the sense that in text property view on crossconnects proper bandwidth will be shown, however on links connecting crossconnects it will show 10Mbps which is the default. This really is a won't fix - we'd need to change how things are rendered to address it. @kthare10
