### ISSUE TITLE
Flukes support to show horizon details for each VM from manifest

### ISSUE THREAD

**Issue by kthare10** [RENCI-NRIG/flukes#26]
Flukes support to show horizon details for each VM from manifest. Horizon details are available in manifest for each VM instance as following parameters:

```
     <j.1:hasHorizonUserName>owner-kthare10-slice2-LRl85wQcnD</j.1:hasHorizonUserName>
     <j.1:hasHorizonUserPwd>v6VAtyFVcU</j.1:hasHorizonUserPwd>
     <j.1:hasHorizonUrl>http://152.54.14.213/dashboard/identity/</j.1:hasHorizonUrl>
```

[manifest.rdf.txt](https://github.com/RENCI-NRIG/flukes/files/3242222/manifest.rdf.txt)

NOTE: renamed manifest file to avoid github from preventing to upload .rdf files

**Comment by ibaldin** [comment]
Horizon properties will be visible in the text. We can also open browser to the URL, however I don't think we can auto-populate user/password, so maybe it is better to leave like this. 

<img width="1167" alt="Screen Shot 2019-06-04 at 3 30 18 PM" src="https://user-images.githubusercontent.com/12304033/58908104-b3908c80-86dd-11e9-8de7-5673d4ab4916.png">
