### ISSUE TITLE
Unknown publisher / untrusted site errors on startup

### ISSUE THREAD

**Issue by paul-ruth** [RENCI-NRIG/flukes#3]
The errors on startup look bad and give a general impression that this is not production quality software.   We should get the appropriate CA or whatever is needed to allow Flukes to boot without error.

**Comment by ibaldin** [comment]
I'll talk to Victor. This is relatively easily fixed if you throw money into it. Need a code-signing certificate from a trusted authority, I think.

**Comment by ibaldin** [comment]
UNC doesn't offer InCommon code-signing certs. Duke does. Talking to Victor about getting one for free, if not, we'll buy a DigiCert one.

**Comment by ibaldin** [comment]
Victor, so what's the best way to proceed with getting InCommon cert through Duke? Or should I just pay to get a DigiCert? I'd rather solve this sooner than later and $300 is not that huge of a burden..

**Comment by ibaldin** [comment]
Ordered GoDaddy code signing cert. Waiting for approval.

**Comment by ibaldin** [comment]
Cert received, warnings went away, except had to deal with re-signing bouncycastle jars according to this:

http://stackoverflow.com/questions/19029575/bouncycastle-cryptography-provider-library-used-with-applet-on-java-7u40

Re-signed jars are stored on geni-images and are copied over the jars created by the build process upon installation (build.xml 957096d19010d76a1e54ea968ef8d74616675fa3)

Waiting on a cert for geni.renci.org to get rid of last warning, alternatively will switch to http:// for registry access.

**Comment by ibaldin** [comment]
Temporarily set registry URL to http://
