### ISSUE TITLE
NDL Checking on Open Request

### ISSUE THREAD

**Issue by paul-ruth** [RENCI-NRIG/flukes#4]
When I open a request it will refuse to open the file if the NDL does not pass some tests.   The problem is that I can not fix the problems without opening the file.    

There needs to be some was to open broken NDL files so that you can fix them.

Paul

**Comment by ibaldin** [comment]
I set up request parser in flukes to be less strict about what it accepts back. It may still barf on certain things, but there will be fewer of them.

**Comment by ibaldin** [comment]
New flukes deployed.
