### ISSUE TITLE
Default BW on broadcast links

### ISSUE THREAD

**Issue by paul-ruth** [RENCI-NRIG/flukes#6]
By default, Flukes sets the requested bandwidth to 0 (zero) for broadcast links.   Interdomain links (at least to AL2S) will fail with a zero bandwidth request.

Probably a request for 0 bandwidth should not be allowed.

**Comment by ibaldin** [comment]
This should be easy to fix.

**Comment by ibaldin** [comment]
I set it to 10Mbps and deployed new code.
